### ISSUE TITLE
I'm getting this when running on windows 10 .

### ISSUE THREAD

**Issue by jwhite** [nilleb/dockerfiles#2]
My docker run command is as follows : 

> docker run -v "c:\sonarqubeData:c:\sonarqube\data" sonarqube  -Dtafa=fsaa

C:\sonarqube>if not x-x == x-x (-Dtafa=fsaa  )  else (java -jar lib/sonar-application-6.2.jar -Dsonar.log.console=true -Dsonar.jdbc.username="sonar" -Dsonar.jdbc.password="sonar" -Dsonar.jdbc.url="" -Dsonar.web.javaAdditionalOpts=" -Djava.security.egd=file:/dev/./urandom" -Dtafa=fsaa )
2017.08.03 15:46:24 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory C:\sonarqube\temp
2017.08.03 15:46:24 INFO  app[][o.s.p.m.JavaProcessLauncher] Launch process[es]: C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.111-1\jre\bin\java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djna.nosys=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube\temp -javaagent:C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.111-1\jre\lib\management-agent.jar -cp ./lib/common/*;./lib/search/* org.sonar.search.SearchServer C:\sonarqube\temp\sq-process400685886108868579properties
2017.08.03 15:46:25 INFO  es[][o.s.p.ProcessEntryPoint] Starting es
2017.08.03 15:46:25 INFO  es[][o.s.s.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2017.08.03 15:46:25 INFO  es[][o.elasticsearch.node] [sonarqube] version[2.3.5], pid[2052], build[90f439f/2016-07-27T10:36:52Z]
2017.08.03 15:46:25 INFO  es[][o.elasticsearch.node] [sonarqube] initializing ...
2017.08.03 15:46:25 INFO  es[][o.e.plugins] [sonarqube] modules [], plugins [], sites []
2017.08.03 15:46:25 WARN  es[][o.s.p.ProcessEntryPoint] Fail to start es
java.lang.IllegalStateException: Failed to obtain node lock, is the following location writable?: [C:\sonarqube\data\es\sonarqube]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:200)
        at org.elasticsearch.node.Node.<init>(Node.java:165)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.sonar.search.SearchServer.start(SearchServer.java:48)
        at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:102)
        at org.sonar.search.SearchServer.main(SearchServer.java:91)
Caused by: java.io.IOException: failed to obtain lock on C:\sonarqube\data\es\sonarqube\nodes\49
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:186)
        ... 6 common frames omitted
Caused by: java.nio.file.NoSuchFileException: C:\sonarqube\data\es\sonarqube\nodes\49
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsLinkSupport.getFinalPath(WindowsLinkSupport.java:82)
        at sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:242)
        at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:836)
        at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:44)
        at org.apache.lucene.store.FSDirectory.<init>(FSDirectory.java:138)
        at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:156)
        at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:109)
        at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:176)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:171)
        ... 6 common frames omitted

**Comment by nilleb** [comment]
@jwhite Try searching google for [`docker volumes windows 10 not writable`](https://www.google.fr/search?q=docker+volumes+windows+10+not+writable&oq=docker+volumes+windows+10+not+writable&gs_l=psy-ab.3...29606.32350.0.32759.13.13.0.0.0.0.199.1421.0j11.11.0....0...1.1.64.psy-ab..2.10.1302...33i22i29i30k1j33i160k1j33i21k1.A2dD24gbNRU)
And see if one of the proposed solutions fits your scenario.

If you find the solution, please report it in the follow (I haven't anymore a Windows OS at reach).
